apiVersion: v1
kind: Service
metadata:
  name: {{ include "vnf-scc-sfc.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vnf-scc-sfc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7000
      protocol: TCP
      name: http
  selector:
    {{- include "vnf-scc-sfc.selectorLabels" . | nindent 4 }}
